version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bibliotheca_chudyana_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network
      
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/bibliotheca_chudyana_db?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=rootpassword
      - spring.jpa.hibernate.ddl-auto=create-drop
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      - my-network  

volumes:
  mysql-data:
  
networks:
  my-network:
    driver: bridge
